### ISSUE TITLE
AWS Error: "ManagedRules with name AWSManagedRulesAmazonIpReputationList by vendor AWS does not exist."

### ISSUE THREAD

**Issue by chrisgilmerproj** [trussworks/terraform-aws-wafv2#23]
When using this module's defaults this error appears during `terraform apply`:

```
WAFNonexistentItemException: ManagedRules with name AWSManagedRulesAmazonIpReputationList by vendor AWS does not exist. Please check your inputs
```

It's odd because the rule is clearly listed here:

- https://docs.aws.amazon.com/cli/latest/reference/wafv2/list-available-managed-rule-groups.html
- https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html

My code is:

```hcl
module "alb_wafv2" {
  source  = "trussworks/wafv2/aws"
  version = "2.0"

  name  = "alb-web-acl"
  scope = "REGIONAL"

  alb_arn       = module.app_alb.alb_arn
  associate_alb = true
}
```

Is this a known issue or something that has happened recently? I don't seem to have an answer for this. Here is the updated code I'm using:

```hcl
module "alb_wafv2" {
  source  = "trussworks/wafv2/aws"
  version = "2.0"

  name  = "alb-web-acl"
  scope = "REGIONAL"

  alb_arn       = module.app_alb.alb_arn
  associate_alb = true
  managed_rules = [
    {
      "excluded_rules" : [],
      "name" : "AWSManagedRulesCommonRuleSet",
      "override_action" : "none",
      "priority" : 10
    },
    {
      "excluded_rules" : [],
      "name" : "AWSManagedRulesKnownBadInputsRuleSet",
      "override_action" : "none",
      "priority" : 30
    },
    {
      "excluded_rules" : [],
      "name" : "AWSManagedRulesSQLiRuleSet",
      "override_action" : "none",
      "priority" : 40
    },
    {
      "excluded_rules" : [],
      "name" : "AWSManagedRulesLinuxRuleSet",
      "override_action" : "none",
      "priority" : 50
    },
    {
      "excluded_rules" : [],
      "name" : "AWSManagedRulesUnixRuleSet",
      "override_action" : "none",
      "priority" : 60
    }
  ]
}
```

**Comment by jsclarridge** [comment]
@chrisgilmerproj That's odd. Which version of the AWS provider are you using? The most recent terratests with AWS provider 3.16 were successful.

So far I haven't been able to reproduce the error. Are you still seeing the same issue?

**Comment by chrisgilmerproj** [comment]
Here's my provider:

```hcl
provider "aws" {
  region  = "us-gov-west-1"
  version = "~> 3.18.0"
}
```

Here's my terraform version:

```sh
$ terraform -version
Terraform v0.13.5
```

This makes me wonder if its an issue with gov-cloud and not commercial.

**Comment by dynamike** [comment]
yeah, that managed ruleset doesn't exist in GovCloud for some reason based on my brief poking at a GovCloud AWS console.

**Comment by chrisgilmerproj** [comment]
Good to know! Might be worth updating the docs to let folks know what to do, otherwise I think we're good to go.

**Comment by chrisgilmerproj** [comment]
Oh, thanks for the quick response folks!

**Comment by dynamike** [comment]
I'll pop a PR up shortly to add a note, let us know if you run into other issues with the module.
