### ISSUE TITLE
No support for TF 14?

### ISSUE THREAD

**Issue by arjitj2** [trussworks/terraform-aws-wafv2#26]
Is there any reason 13 is specifically required, instead of 13+ ?

**Comment by gxtruitt** [comment]
I'm wondering the same thing; upgraded my dev machine to Terraform 0.14.3 and can no longer use this module. Thank you for providing it though!

**Comment by dynamike** [comment]
I'm working through our modules adding support slowly. Keep on the looks out for updates this week.
