### ISSUE TITLE
AWS GovCloud now supports AWSManagedRulesAmazonIpReputationList

### ISSUE THREAD

**Issue by elljdotmil** [trussworks/terraform-aws-wafv2#36]
Greetings Trussels,

> As of 12/2/2020, AWS GovCloud does not support the AWSManagedRulesAmazonIpReputationList managed rule set, which is enabled by default in this module. Until AWS supports that rule set, you will need to define your own managed_rules.

We experienced this same issue in GovCloud when previously trying AWSManagedRulesAmazonIpReputationList.

I tried AWSManagedRulesAmazonIpReputationList today (Feb 10 2021) in GovCloud (us-gov-west-1) and it appears that AWSManagedRulesAmazonIpReputationList is now supported. I can't find anything on AWS' docs to confirm, but I was able to successfully apply it via terraform on one of my projects.

Here is a screenshot of it in the AWS Console as well
<img width="823" alt="Screen Shot 2021-02-10 at 6 52 05 PM" src="https://user-images.githubusercontent.com/59453511/107588132-159ed600-6bd1-11eb-91b8-7229130f8f0f.png">

**Comment by dynamike** [comment]
You're the best. I'll update the docs.
