### ISSUE TITLE
Unable to block all by default

### ISSUE THREAD

**Issue by pr1ntr** [trussworks/terraform-aws-wafv2#40]
It appears that 
```
default_action {
  allow {}
}
```
is hardcoded. AWS doesn't allow me to create an ipset with 0.0.0.0/0. Is there a different way to accomplish this with this module?

**Comment by dynamike** [comment]
You can see a terraform workaround for blocking 0.0.0.0/0 in the examples 
https://github.com/trussworks/terraform-aws-wafv2/blob/master/examples/alb/main.tf#L1

It uses a range and formatlist to generate /8s for all ips. Does that help?

**Comment by pr1ntr** [comment]
aah that makes sense. I ended up just forking and changing allow {} to block {}. I wonder if this can be parameterized in 0.14.
