### ISSUE TITLE
Error while doing association with ALB

### ISSUE THREAD

**Issue by chandankashyap19** [trussworks/terraform-aws-wafv2#46]
Hi, Thanks for great work.
Today, I tried to play with module and tried to use with ALB. The creation of WAFv2 with few rules got access and also creation of ALB also got succeeded. 
But during the association of Wafv2 with ALB its starts complaining me the issue. I have used examples/alb/main.tf.
The error , I am getting is as below.

```
eval: *terraform.EvalSequence, err: InvalidParameter: 1 validation error(s) found.
 minimum field size of 20, AssociateWebACLInput.ResourceArn.
```

I am not able understand the exact error. Pls help.

**Comment by jsclarridge** [comment]
@chandankashyap19 Could you post a copy of the configuration that's generating the error, as well as the version of Terraform and AWS provider you're using?
