### ISSUE TITLE
How to Use with Geographic Rules

### ISSUE THREAD

**Issue by fdamstra** [trussworks/terraform-aws-wafv2#73]
Can this module be used to also restrict traffic to geographic regions such as countries? or deny based on country?

Can you give an example?

**Comment by dynamike** [comment]
The examples directory has a way that it can be used. You define a `aws_wafv2_rule_group` which specifies a list of `country_codes` that you can restrict or allow traffic on. See https://github.com/trussworks/terraform-aws-wafv2/blob/main/examples/alb/main.tf#L173

You can then pass this into this module in the `group_rules` variable. See https://github.com/trussworks/terraform-aws-wafv2/blob/main/examples/alb/main.tf#L82. 

Let me know if that doesn't make sense.

**Comment by fdamstra** [comment]
Thank you very much! I missed the examples directory.
