### ISSUE TITLE
Support for Scope Down Statements

### ISSUE THREAD

**Issue by ybudweiser** [trussworks/terraform-aws-wafv2#85]
Is it possible to enhance the Rule Object to include a scope_down_statement so that particular requests can be excluded from the rule group. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#scope_down_statement
https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-scope-down-statements.html
{
    "excluded_rules": [],
    "name": "AWSManagedRulesCommonRuleSet",
    "override_action": "none",
    "priority": 10,
   "scope_down_statement": 
  }

**Comment by rpdelaney** [comment]
@ybudweiser If you can send us a pull request, we'll take a look!
