### ISSUE TITLE
Support Custom Response status code and headers on block action

### ISSUE THREAD

**Issue by aairey** [trussworks/terraform-aws-wafv2#86]
The terraform resource supports it already, please update the module to support it as well.

https://github.com/hashicorp/terraform-provider-aws/issues/18754

**Comment by rpdelaney** [comment]
Hello @aairey ! Just to make sure we understand, you want an input variable that will pass-through to the `custom_response_body` block described [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#custom-response-body). Is that right?

**Comment by aairey** [comment]
Correct!

**Comment by rpdelaney** [comment]
Ok, got it. That seems like something we'd like to support. I'll add it to our roadmap for engineers not on client projects to take on; in the mean time, I'd be happy to review a PR :)

**Comment by rpdelaney** [comment]
I'm not seeing support in this module for a `custom_response` field. I think that may have to be added as well.

**Comment by rpdelaney** [comment]
@aairey We recognize the value of this, but it's not something we need at the moment. If you can send us a PR we'll be happy to take a look :)

**Comment by xgt001** [comment]
hi @rpdelaney , would you be interested in accepting [my PR](https://github.com/trussworks/terraform-aws-wafv2/pull/120). If this is something you can see being accepted, I am happy to refine it and complete this piece by adding support to JSON and HTTP response bodies , as well as adding support for multiple response bodies
