### ISSUE TITLE
How to block all managed rules but otherwise allow traffic?

### ISSUE THREAD

**Issue by dangarthwaite** [trussworks/terraform-aws-wafv2#98]
If I set default_action to "block" all traffic is blocked - even traffic that doesn't match a managed rule.
If I set default_action to "allow" all traffic is allowed - even traffic that does match a managed rule.

I see one closed issue related to this.  I suspect the answer is that an additional custom "allow" rule with low priority must be created.  What is the simplest way to accomplish that with this module?

**Comment by rpdelaney** [comment]
@dangarthwaite Which issue are you referring to?
